### ISSUE TITLE
!!!!!!!! Unknown buildconfig variable 'build-timestamp'

### ISSUE THREAD

**Issue by WalterWampe** [tpill90/battlenet-lancache-prefill#103]
Sorry for the !s, its from the log....

**Describe the bug**
The command `docker run --rm --name prefill-battlenet --net=host --volume /vmdisk/volumes/lancache/BattleNetPrefill:/Config tpill90/battlenet-lancache-prefill:latest prefill` throws this error: `!!!!!!!! Unknown buildconfig variable 'build-timestamp'` and redownloads the whole 80GB every time I run the container.

```
docker run --rm --name prefill-battlenet --net=host --volume /vmdisk/volumes/lancache/BattleNetPrefill:/Config tpill90/battlenet-lancache-prefill:latest prefill
[11:01:23 AM] Prefilling 1 products 

[11:01:23 AM] Starting Diablo 4
Detecting Lancache server...
[11:01:23 AM] Detected Lancache server at level3.blizzard.com [192.168.1.202]

Getting latest config files...
!!!!!!!! Unknown buildconfig variable 'build-timestamp'
Building Archive Indexes...
Determining files to download...
[11:01:32 AM] Retrieved product metadata                         08.9542
[11:01:32 AM] Downloading 80.98 GiB
Downloading..: 0%
```

**Additional Details**
 - Ubuntu
 - Region :  Germany

**Screenshots**

**Comment by tpill90** [comment]
Released in [v1.7.0](https://github.com/tpill90/battlenet-lancache-prefill/releases/tag/v1.7.0)
