### ISSUE TITLE
prefill stucks at 99%, retries are failing

### ISSUE THREAD

**Issue by n300home** [tpill90/battlenet-lancache-prefill#115]
**Describe the bug**
Hi,
I'm using all 3 of your launcher/lancache prefiller. I have the problem, that game downloads often (not always) becomes stucking at 99% and fails after some retrials. In game launcher it self there is no issue, because most of the content is already on lancache.
I'm experiencing that in all 3 prefillers in some (not all) download selected games.

Basically it's not a big issue, because lancache is quit good filled. But the prefiller won't mark failed downloads as done. Therefore it downloads always the full bundle for each failed game again and again, which stresses my QNAP (where lancache is running as docker container) a little bit ;)

**Additional Details**
 - Platform you are running BattleNetPrefill on:  Windows Server (VM o QNAP)
 - Region : Germany

**Screenshots**
![image](https://github.com/tpill90/battlenet-lancache-prefill/assets/25461480/8b81c18d-e8c0-4e73-b5d9-7d9b1400a731)

**Comment by tpill90** [comment]
Hi @n300home,

I believe that your issue is related to this one in SteamPrefill : [issues/349](https://github.com/tpill90/steam-lancache-prefill/issues/349).  I haven't gotten around to porting those changes over to BattlenetPrefill and EpicPrefill, but I'm going to bet that when I do it will solve your issue.

I'll see if I can take a crack at it when I have some time in the next few days.

**Comment by tpill90** [comment]
Sorry for the late reply on this, I actually did start this and it is implemented. I've just gotten sidetracked on finishing up everything I need to do before releasing. I'll try to get this finished up in the next few days

**Comment by tpill90** [comment]
The fix for this has been included in [https://github.com/tpill90/battlenet-lancache-prefill/releases/tag/v2.0.0](v2.0.0).  If this doesn't fix it for you, please feel free to reopen the issue.
