### ISSUE TITLE
Prefill Diablo IV and World of Warcraft error out

### ISSUE THREAD

**Issue by kevsaenz** [tpill90/battlenet-lancache-prefill#121]
**Describe the bug**
Running prefill both Diablo IV and World of Warcraft error near the end of the download.  Unsure if the error occurs for other games in Battlenet. 

Also could the Beta of World of Warcraft, and the Mists of Pandaria remix impact the caching options?

**Additional Details**
 - Platform: Windows 11
 - Discord Username: Elerunne
 - Region : Australia

**Screenshots**
![image](https://github.com/tpill90/battlenet-lancache-prefill/assets/11770570/dc1888c9-1cf6-4b87-8b32-1ce8663dd92d)

**Comment by kevsaenz** [comment]
unsure if the error occurs for other games in Battlenet. Also could the Beta of World of Warcraft, and the Mists of Padaria remix impact the caching options?

**Comment by tpill90** [comment]
> Also could the Beta of World of Warcraft, and the Mists of Pandaria remix impact the caching options?

Neither the Beta nor Pandaria should have any affect on this.  With the way that Battlenet stores files on their CDN there is a lot of sharing between different "versions" or "branches" such that their files are one in the same.

**Comment by kevsaenz** [comment]
Problem resolved there was an issue with my NAS throwing errors. Resolved those errors by running xfs-repair against a drive, and running a parity check. thanks
