### ISSUE TITLE
OSX Release Folder Structure Bugged

### ISSUE THREAD

**Issue by skhati1** [tpill90/battlenet-lancache-prefill#16]
Downloading the latest OSX release and extracting it yielded files that looked like these. Had to manually remove the folder name prefix to get it working! 

<img width="847" alt="May 8, 2022 at 118 PM" src="https://user-images.githubusercontent.com/10587654/170027403-da48cb96-137d-44e5-81e3-578d15cabf74.png">

**Comment by tpill90** [comment]
I'm not quite sure what the issue you're running to here is.  Is this something specific to how OSX handles zip files?

I pulled down both v1.0.0 and v.1.10 artifacts for OSX, and there is no prefixing on the zips when opening in 7zip on Windows : 
![image](https://user-images.githubusercontent.com/766513/170837871-2b311d8b-f71d-4261-9861-4b95c557dd74.png)

**Comment by skhati1** [comment]
Maybe the difference is forward slash vs backwards slash on windows vs linux / osx?
