### ISSUE TITLE
Download hangs and won't finish

### ISSUE THREAD

**Issue by tpill90** [tpill90/battlenet-lancache-prefill#32]
![image](https://user-images.githubusercontent.com/766513/184386211-3bda031b-be14-4dd0-8ac8-f4aaa82e5143.png)

```
2022/08/12 11:38:15 [error] 1937#1937: *363188 upstream timed out (110: Connection timed out) while reading upstream, client: 192.168.168.200, server: , request: "GET /tpr/fore/data/83/2e/832e640c8add75816edaf21e452fd165 HTTP/1.1", subrequest: "/tpr/fore/data/83/2e/832e640c8add75816edaf21e452fd165", upstream: "[http://8.238.38.254:80/tpr/fore/data/83/2e/832e640c8add75816edaf21e452fd165](http://8.238.38.254/tpr/fore/data/83/2e/832e640c8add75816edaf21e452fd165)", host: "level3.blizzard.com"
```

**Comment by Artalius** [comment]
[LanCache-Blizz-Diablo2-Access.log.txt](https://github.com/tpill90/battlenet-lancache-prefill/files/9409119/LanCache-Blizz-Diablo2-Access.log.txt)
[LanCache-Blizz-Diablo2-Error.log.txt](https://github.com/tpill90/battlenet-lancache-prefill/files/9409120/LanCache-Blizz-Diablo2-Error.log.txt)

**Comment by Artalius** [comment]
![image](https://user-images.githubusercontent.com/42320740/186224102-f0bfc503-508f-47c6-a9da-7fc1a13b8a5b.png)

**Comment by tpill90** [comment]
Closing this for now, as the issues don't seem to have come up again in quite some time, and I'm unable to reproduce the issue.

As always, feel free to re-open if this continues to occur.
