### ISSUE TITLE
[Feature request] Implementing auto-update

### ISSUE THREAD

**Issue by soonic6** [tpill90/battlenet-lancache-prefill#53]
My Usecase:
I use prefill every night to pre fill my lancache. A cronjob starts up an LXC, runs an [update script](https://github.com/soonic6/steam-lancache-prefill-update), runs the prefill and shut the LXC down.

Motivation:
A version check is still implemented, but a quiet (maybe optional) autoupdate can be usefull for a headless lancache-prefill.

Maybe https://github.com/soonic6/steam-lancache-prefill-update could be implemented for auto-updates.

**Comment by tpill90** [comment]
Released in [v1.6.0](https://github.com/tpill90/battlenet-lancache-prefill/releases/tag/v1.6.0)
