### ISSUE TITLE
[Feature request] option for monochrome output

### ISSUE THREAD

**Issue by soonic6** [tpill90/battlenet-lancache-prefill#54]
The color generates cryptic outputs in my logfiles, maybe an option for a monochrome output will be possible?

![image](https://user-images.githubusercontent.com/73687921/189481793-1ea183e6-f596-4511-91f5-ed179ba626d8.png)

see also: https://github.com/tpill90/steam-lancache-prefill/issues/128

**Comment by tpill90** [comment]
Released in [v1.6.0](https://github.com/tpill90/battlenet-lancache-prefill/releases/tag/v1.6.0)
