### ISSUE TITLE
Linux: update.sh apply chmod +x to SteamPrefill on update

### ISSUE THREAD

**Issue by kizmat** [tpill90/battlenet-lancache-prefill#63]
If update.sh is run, it would be helpful if chmod +x is re-applied to SteamPrefill.

If you wanted it to be more security conscious before the upgrade you get check if the existing older binary has the execute flag, and if it does, set chmod +x at the end of the upgrade. If not, then leave it be.

For me as a user, every time the binary is replaced with a new version, I have to re-apply chmod +x to SteamPrefill or my scripts will break.

Granted I could script the chmod +x myself as well, its a nice to have though ^^

**Comment by tpill90** [comment]
Taken care of in pull request #85
