### ISSUE TITLE
Feature request - Total data downloaded

### ISSUE THREAD

**Issue by billthecatt** [tpill90/battlenet-lancache-prefill#75]
If you could, print this at the end of each run, then we could see what du -h shows and compare to see what's in the cache on disk vs just now downloaded.

**Comment by tpill90** [comment]
Closing this out, as now that BattlenetPrefill is stable there isn't as much of a need for something like this.

**Comment by tpill90** [comment]
[https://github.com/tpill90/battlenet-lancache-prefill/releases/tag/v2.0.0](v2.0.0)
