### ISSUE TITLE
Feature Request - Add Support for Diablo 4

### ISSUE THREAD

**Issue by Serverfrog** [tpill90/battlenet-lancache-prefill#76]
Diablo 4 is coming/is downloadable
It is found under the Path of `/tpr/fenris`. Due to the nature of the Naming Scheme of other Activision-Blizzard Games it seemse like this is the Productname on their CDN

**Comment by Serverfrog** [comment]
Postpone till 06.06.2023, because currently only the Tact Code `fenris_beta` is accessible (due to the fact that `fenris` is not out yet)

**Comment by tpill90** [comment]
Released in [v1.6.0](https://github.com/tpill90/battlenet-lancache-prefill/releases/tag/v1.6.0)
