### ISSUE TITLE
Feature Request - Add support to Download Games via their Productname

### ISSUE THREAD

**Issue by Serverfrog** [tpill90/battlenet-lancache-prefill#77]
It would be awesome as an Option (before a Product is Implemented) to fill the cache when the Productname is known.

Os Product name i mean things like `odin` for Warzon or `w3` for Warcraft 3 Reforged.

This would make it possible to fill the cache with products that are not already implemented into this software, but still can be used by more advanced Administrators

**Comment by tpill90** [comment]
@Serverfrog Could you give me a bit more background on your specific use case for this request?  What about it would you find useful in how you use this prefill?  I'm assuming this is likely for prefilling beta versions?

**Comment by Serverfrog** [comment]
for example, or for games that are not included because different reasons. for example, i dont know if its currently possible to prefill non-reforged WC3 or StarCraft. I think that would be a nice setup so people can test for you what the correct Product Names are and then there is also an alternative to not implement some/make changes for same temporary ones

**Comment by tpill90** [comment]
To the best of my knowledge there is no such thing as "Starcraft" anymore, it's only Starcraft Remastered `s1`.  And no "Warcraft 3", only "Warcraft 3 : Reforged" with `w3`.  Blizzard replaced both of those games completely, with no way of downloading or installing the original version.  I've dug around in the files for Starcraft enough to see that there is nothing except the remastered version on their CDNs.

Blizzard does publish the available product codes via API, and there is this site that tracks them all : [Blizztrack](https://blizztrack.com/).  The majority of the product codes are useless, they're not labeled with anything identifying as to what they are, and the majority of them are either encrypted or you simply cannot download them at all.  The ones that are useful are available to prefill via `select-apps` or previously listed via `list-products`.  

I've researched extensively as to how Battle.net handles their "download upcoming patches ahead of time" feature, and I haven't been able to determine exactly how it works.  It doesn't appear to be its own product code, but rather part of the existing code in some manner.
