### ISSUE TITLE
Control + C doesn't pause prefill after select-apps

### ISSUE THREAD

**Issue by DecusAnima** [tpill90/battlenet-lancache-prefill#99]
Control + C does not pause the prefill if it started after select-apps command is ran. Reboot necessary to stop the prefill.

**Additional Details**
 - Ubuntu 22.02 Server
 - decusanima
 - US Central

**Comment by tpill90** [comment]
Released in [v1.7.0](https://github.com/tpill90/battlenet-lancache-prefill/releases/tag/v1.7.0)
